### ISSUE TITLE
Convert README and CHANGES to markdown

### ISSUE THREAD

**Issue by ericof** [plone/plone.app.caching#114]

**Comment by stevepiercy** [comment]
Thinking ahead, outside of this issue:

1. Is the ultimate goal to move this into `plone/documentation` or keep it separate?
2. If separate, should it be a git submodule that gets pulled into `plone/documentation`, else how would its docs be published?

**Comment by mauritsvanrees** [comment]
Briefly discussed on Discord: moving it to `plone/documentation` as real content seems best.  No git submodules.

**Comment by stevepiercy** [comment]
Also for future reference, in general:

- If the docs require autodoc or other Sphinx extension to build—such as volto, plone.restapi, and plone.api—then keep the docs where they are and use a git submodule to pull in both the code and the docs.
- If the docs do not require the code to build, then just move them into `plone/documentation` to centralize.
