### ISSUE TITLE
Caching control panel formControls are missing on live environment

### ISSUE THREAD

**Issue by neilferreira** [plone/plone.app.caching#27]
Hello

I've been using plone.app.caching on a large variety of websites but have never had this issue come up before.

On one of my live environments the formControls div (https://github.com/plone/plone.app.caching/blob/master/plone/app/caching/browser/controlpanel.pt#L632) is missing on the caching control panel.

It is not being removed by javascript and simply is not in the page source.  There is no condition around it to hide it.

Any ideas?

**Comment by gforcada** [comment]
Maybe the theme rules? If you are using the very same version on different websites and on all but one is not there it may be a theme rule that removes it?

**Comment by neilferreira** [comment]
I've realized this is not a problem with p.a.caching! apologies :)
