### ISSUE TITLE
remove alleged support for gzip compression

### ISSUE THREAD

**Issue by vangheem** [plone/plone.app.caching#4]
Zope doesn't do a good job at it and it's silly to do it at the application layer anyways.

Just remove all reference to it.

**Comment by gforcada** [comment]
:+1: given that *any* sane deployment will have an HTTP server in front of Plone, gzip can and should be done there, even more if you have HTTP Server -> Caching -> Balancer.

**Comment by jensens** [comment]
indeed, also removing its prevents people from double zipping

**Comment by vangheem** [comment]
alright, PR made: https://github.com/plone/plone.app.caching/pull/16
