### ISSUE TITLE
install add on from admin

### ISSUE THREAD

**Issue by fsacchi74** [plone/plone.app.caching#82]
Hello,
with same add-on we ha this error,
when we try install them from admin.

Traceback (innermost last):
Module ZPublisher.WSGIPublisher, line 162, in transaction_pubevents
Module ZPublisher.WSGIPublisher, line 371, in publish_module
Module ZPublisher.WSGIPublisher, line 274, in publish
Module ZPublisher.mapply, line 85, in mapply
Module ZPublisher.WSGIPublisher, line 63, in call_object
Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 689, in call
Module Products.CMFPlone.controlpanel.browser.quickinstaller, line 454, in install_product
Module Products.GenericSetup.tool, line 405, in runAllImportStepsFromProfile

    traceback_info: profile-redturtle.volto:default
    Module Products.GenericSetup.tool, line 1483, in _runImportStepsFromContext
    Module Products.GenericSetup.tool, line 1295, in _doRunImportStep
    traceback_info: plone.app.registry
    Module plone.app.registry.exportimport.handler, line 79, in importRegistry
    traceback_info: registry.xml
    Module plone.app.registry.exportimport.handler, line 125, in importDocument
    Module plone.app.registry.exportimport.handler, line 228, in importRecord
    traceback_info: record name: plone.app.caching.terseCaching.plone.content.dynamic.etags
    KeyError: 'Record plone.app.caching.terseCaching.plone.content.dynamic.etags references field for record plone.app.caching.terseCaching.etags, which does not exist'

We have python 3.7 and plone 5.2.4, and plone.app.caching 3.0.0a3 version.

Thanks.
Federica

**Comment by mauritsvanrees** [comment]
Can you describe the steps you follow?
When I create a fresh Plone Site, plone.app.caching is already installed, so I cannot install it manually.

Latest version is 3.0.0a5. Maybe try with that, although it does not look like anything relevant was changed.

Also, note that version 3 is not officially support on Plone 5.2. It is meant for Plone 6. But it should be okay.

Ah, now that I look more closely, I think plone.app.caching is missing an upgrade step for the new terse caching. So if you start with standard Plone 5.2.4 (or 5.2.5) and start using plone.app.caching version 3, you may run into this. (I have not tried it, but I think it will indeed cause your problem.)
@jensens Can you have a look at this?

**Comment by fsacchi74** [comment]
When we created the Plone site, we installed plona.app.caching from the admin.

We also tried version 3.0.0a5, but nothing has changed.

Thanks
Federica

**Comment by mauritsvanrees** [comment]
To reproduce:

- Use the Plone coredev buildout 6.0 with a checkout of plone.app.caching.
- Checkout tag 2.0.8 of plone.app.caching.
- Create a Plone Site.
- Checkout plone.app.caching master and restart the site.
- In the caching control panel go to the Import Settings tab.
- Pick one of the standard caching profiles to install.
- You get the above KeyError.

I think the best would be to add an upgrade step in `plone.app.caching`. I am looking into it now.

Workaround: in the ZMI go to `portal_setup`, Import tab, and import the `plone.app.caching:default` profile.
