### ISSUE TITLE
Remove or replace resourceRegistries etag

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.caching#93]
This was initially removed in Plone 5.2 because it was for the old `portal_css/javascripts` tools. I restored it in proper form for the "new" resource registries of 5.2 in PR #65, basically reading the `timestamp.txt`. But with Plone 6  the `timestamp.txt` in `portal_resources` is not there and not needed.

So what do we do with this etag? Remove it? Or can it be replaced with an etag that works on Plone 6?

The point of this etag is to prevent this scenario:

- You have an html page in the Varnish cache, and this points to a resource with a unique hash.
- You change the resource, probably by a change on the file system, and restart Plone.
- A user requests the page, Varnish returns the cached version, and then the browser requests the resource with the old unique hash, so it gets the old version.

If the page is cached using etags, then the job of the `resourceRegistries` etag, is to return a different value, because it sees the resource has changed.

Can we come up with a sane replacement of this etag?

**Comment by mauritsvanrees** [comment]
Starting with Plone 6.0.4, the `portal_registry` will have a modification time, and it is updated whenever the Resource Registries change or an add-on is installed.  See https://github.com/plone/Products.CMFPlone/pull/3771.  We could use this time in the etag.

@jensens Does this make sense to you?

**Comment by jensens** [comment]
I think this is an excellent idea!
