### ISSUE TITLE
Move plone.restapi mapping

### ISSUE THREAD

**Issue by ericof** [plone/plone.app.caching#97]
Currently the [mapping of classes to rulesets for plone.restapi services](https://github.com/plone/plone.app.caching/blob/master/plone/app/caching/caching.zcml#L137) is done in this package, this should be moved to `plone.restapi`

**Comment by mauritsvanrees** [comment]
This was done in Plone 6. See:

- https://github.com/plone/plone.app.caching/pull/100
- https://github.com/plone/plone.restapi/pull/1414
